import json
import boto3

print("Loading function")

s3 = boto3.client("s3")
ec2 = boto3.client("ec2", region_name = "eu-west-3")
instance_id = "i-123456789" # replace with your instance ID

def lambda_handler(event, context):
    # Event generated by a change in the S3
    bucket = event['Records'][0]['s3']['bucket']['name']
    key = event['Records'][0]['s3']['object']['key']
    
    # Check if the event corresponds to a new raw json messages from Reddit:
    if key == "reddit-posts.json":
        try:
            ec2.start_instances(InstanceIds=[instance_id])
            print(f'Started EC2 instance {instance_id}')
            
            return {
                'statusCode': 200,
                'body': 'EC2 instance started successfully.'
            }
        except Exception as e:
            print(f'Error starting EC2 instance {instance_id}: {str(e)}')
            raise e
    
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }
